config/routes.rb
Rails.application.routes.draw do

  get '/customers/my_page' => 'public/customers#show'
  get '/customers/information/edit' => 'public/customers#edit'
  patch '/customers/information' => 'public/customers#update'
  get '/customers/unsubscribe' => 'public/customers#unsubscribe'
  patch '/customers/withdraw' => 'public/customers#withdraw'

  get '/orders/complete' => 'public/orders#complete'

  scope module: :public do
    resources:cart_items,only:[:index,:update,:destroy,:create] do
      collection do
        delete "destroy_all"
      end
    end
    resources:addresses,only:[:index,:edit,:create,:update,:destroy]
    resources:items,only:[:index,:show]
    resources:orders,only:[:new,:index,:show,:create]
  end

  post '/orders/comfirm' => 'public/orders#comfirm'
  get '/orders/comfirm' => 'public/orders#comfirm'


    root 'public/homes#top'
    get "/about" => "public/homes#about",as:"about"

    get "/admin" => "admin/homes#top"



  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }

  devise_for :customers,skip:[:passwords],controllers:{
    registrations:"public/registrations",
    sessions:"public/sessions"
  }

  namespace :admin do
    resources:orders,only:[:show,:update]
    resources:genres,only:[:create,:index,:edit,:update]
    resources:items,only:[:index,:new,:create,:show,:edit,:update,:destroy]
    resources:customers,only:[:index,:show,:edit,:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates:postal_code,presence:true
  validates:address,presence:true
  validates:name,presence:true

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  has_one_attached:image
  
  

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  has_one_attached:image
  belongs_to :customer
  belongs_to :item
  
  def sub_total
    item.add_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses,dependent: :destroy
  has_many :cart_items,dependent: :destroy
  has_many :orders,dependent: :destroy

  validates:last_name,presence:true
  validates:first_name,presence:true
  validates:last_name_kana,presence:true
  validates:first_name_kana,presence:true
  validates:postal_code,presence:true
  validates:address,presence:true
  validates:telephone_number,presence:true


def active_for_authentication?
  super && (is_deleted == false)
end

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates:name,presence:true

  has_many :items,dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached:image
  belongs_to :genre
  has_many :cart_items,dependent: :destroy
  has_many :order_details,dependent: :destroy


  validates:name,presence:true
  validates:introduction,presence:true
  validates:price,presence:true
  validates:is_active, inclusion: [true, false]

  def add_tax_price
    (self.price * 1.10).round
  end

  def get_image(width,height)
    unless image.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
    end
     image.variant(resize_to_limit:[width,height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details,dependent: :destroy
  belongs_to :customer

  validates:postal_code,presence:true
  validates:address,presence:true
  validates:name,presence:true

  enum payment_method:{credit_card:0,transfer:1}
  enum status:{deposit_wait:0,deposit:1,making:2,shipping_preparation:3,shipping:4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  validates:price,presence:true
  validates:amount,presence:true

  enum maiking_status:{impossible:0,waiting:1,maiking:2,complete:3}

  def sub_total
    item.add_tax_price * amount
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number)
  end



end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page]).order('created_at DESC')

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])

  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end
  
  def destroy
    @item = Item.find(params[:id])
    redirect_to admin_items_path
    @item.destroy
  end

  private
  def item_params
    params.require(:item).permit(:genre_id,:name,:introduction,:price,:is_active,:image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?



  def after_sign_in_path_for(resource)
    "/"
  end

  def after_sign_out_path_for(resource)
    "/"
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="ml-5 mb-3 font-weight-bold bg-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</div>
  </div>
  <%= form_with model:@customer,url:admin_customer_path do |f| %>
  <div class="row mb-auto">
    <label class="col-sm-4 font-weight-bold">会員ID</label>
    <div class="col-sm-8">
      <%= @customer.id %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-4 font-weight-bold">氏名</label>
    <div class="col-sm-8">
      <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %>  <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-4 font-weight-bold">フリガナ</label>
    <div class="col-sm-8">
      <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana" %>  <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana" %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-4 font-weight-bold">郵便番号</label>
    <div class="col-sm-8">
      <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code" %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-4 font-weight-bold">住所</label>
    <div class="col-sm-8">
      <%= f.text_field :address, autofocus: true, autocomplete: "address" %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-4 font-weight-bold">電話番号</label>
    <div class="col-sm-8">
      <%= f.text_field :telephone_number, autofocus: true, autocomplete: "telephone_number" %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-4 font-weight-bold">メールアドレス</label>
    <div class="col-sm-8">
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-4 font-weight-bold">会員ステータス</label>
    <div class="col-sm-4">
      <%= f.radio_button :is_deleted, :false %><%= "有効" %>
    </div>
    <div class="col-sm-4">
      <%= f.radio_button :is_deleted, :true %><%= "退会" %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-4 font-weight-bold"></label>
    <div class="col-sm-8">
      <%= f.submit "変更を保存",class:"btn btn-success" %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="ml-5 mb-3 font-weight-bold bg-light">会員一覧</div>
  </div>
  <table class="table">
  <thead class="table-active">
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
    <tr>
      <td>
        <%= customer.id %>
      </td>
      <td>
        <%= link_to admin_customer_path(customer.id) do %>
        <%= customer.last_name %><%= customer.first_name %>
        <% end %>
      </td>
      <td>
        <%= customer.email %>
      </td>
      <td>
        <% if customer.is_deleted == true %>
           <%= "退会" %>
        <% else %>
           <%= "有効" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
 </table>
<%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="ml-5 mb-3 font-weight-bold bg-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</div>
  </div>

  <div class="row mb-auto">
    <label class="col-sm-4 font-weight-bold">会員ID</label>
    <div class="col-sm-8">
      <%= @customer.id %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-4 font-weight-bold">氏名</label>
    <div class="col-sm-8">
      <%= @customer.last_name %> <%= @customer.first_name %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-4 font-weight-bold">フリガナ</label>
    <div class="col-sm-8">
      <%= @customer.last_name_kana %> <%= @customer.first_name_kana %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-4 font-weight-bold">郵便番号</label>
    <div class="col-sm-8">
      <%= @customer.postal_code %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-4 font-weight-bold">住所</label>
    <div class="col-sm-8">
      <%= @customer.address %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-4 font-weight-bold">電話番号</label>
    <div class="col-sm-8">
      <%= @customer.telephone_number %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-4 font-weight-bold">メールアドレス</label>
    <div class="col-sm-8">
      <%= @customer.email %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-4 font-weight-bold">会員ステータス</label>
    <div class="col-sm-8">
      <% if @customer.is_deleted == true %>
        <%= "退会" %>
      <% else %>
        <%= "有効" %>
      <% end %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-4 font-weight-bold"></label>
    <div class="col-sm-4">
      <%= link_to "編集する",edit_admin_customer_path(@customer.id),class:"btn btn-success" %>
    </div>
    <div class="col-sm-4">
      <%= link_to "注文履歴一覧を見る",edit_admin_customer_path(@customer.id),class:"btn btn-primary" %>
    </div>
  </div>
</div>