config/routes.rb
Rails.application.routes.draw do

  get '/customers/my_page' => 'public/customers#show'
  get '/customers/information/edit' => 'public/customers#edit'
  patch '/customers/information' => 'public/customers#update'
  get '/customers/unsubscribe' => 'public/customers#unsubscribe'
  patch '/customers/withdraw' => 'public/customers#withdraw'

  get '/orders/complete' => 'public/orders#complete'

  scope module: :public do
    resources:cart_items,only:[:index,:update,:destroy,:create] do
      collection do
        delete "destroy_all"
      end
    end
    resources:addresses,only:[:index,:edit,:create,:update,:destroy]
    resources:items,only:[:index,:show]
    resources:orders,only:[:new,:index,:show,:create]
  end

  post '/orders/comfirm' => 'public/orders#comfirm'
  get '/orders/comfirm' => 'public/orders#comfirm'


    root 'public/homes#top'
    get "/about" => "public/homes#about",as:"about"

    get "/admin" => "admin/homes#top"



  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }

  devise_for :customers,skip:[:passwords],controllers:{
    registrations:"public/registrations",
    sessions:"public/sessions"
  }

  namespace :admin do
    resources:orders,only:[:show,:update]
    resources:genres,only:[:create,:index,:edit,:update]
    resources:items,only:[:index,:new,:create,:show,:edit,:update,:destroy]
    resources:customers,only:[:index,:show,:edit,:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates:postal_code,presence:true
  validates:address,presence:true
  validates:name,presence:true

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  has_one_attached:image
  
  

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  has_one_attached:image
  belongs_to :customer
  belongs_to :item
  
  def sub_total
    item.add_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses,dependent: :destroy
  has_many :cart_items,dependent: :destroy
  has_many :orders,dependent: :destroy

  validates:last_name,presence:true
  validates:first_name,presence:true
  validates:last_name_kana,presence:true
  validates:first_name_kana,presence:true
  validates:postal_code,presence:true
  validates:address,presence:true
  validates:telephone_number,presence:true


def active_for_authentication?
  super && (is_deleted == false)
end

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates:name,presence:true

  has_many :items,dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached:image
  belongs_to :genre
  has_many :cart_items,dependent: :destroy
  has_many :order_details,dependent: :destroy


  validates:name,presence:true
  validates:introduction,presence:true
  validates:price,presence:true
  validates:is_active, inclusion: [true, false]

  def add_tax_price
    (self.price * 1.10).round
  end

  def get_image(width,height)
    unless image.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
    end
     image.variant(resize_to_limit:[width,height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details,dependent: :destroy
  belongs_to :customer

  validates:postal_code,presence:true
  validates:address,presence:true
  validates:name,presence:true

  enum payment_method:{credit_card:0,transfer:1}
  enum status:{deposit_wait:0,deposit:1,making:2,shipping_preparation:3,shipping:4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  validates:price,presence:true
  validates:amount,presence:true

  enum maiking_status:{impossible:0,waiting:1,maiking:2,complete:3}

  def sub_total
    item.add_tax_price * amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page]).order('created_at DESC')

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])

  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end
  
  def destroy
    @item = Item.find(params[:id])
    redirect_to admin_items_path
    @item.destroy
  end

  private
  def item_params
    params.require(:item).permit(:genre_id,:name,:introduction,:price,:is_active,:image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController

  protected
  def after_sign_in_path_for(resource)
    admin_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?



  def after_sign_in_path_for(resource)
    "/"
  end

  def after_sign_out_path_for(resource)
    "/"
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="ml-5 mb-3 font-weight-bold bg-light">ジャンル編集</div>
  </div>

  <div class="row mb-3">
    <label class="col-sm-2 font-weight-bold">ジャンル名</label>
      <div class="col-sm-10">
        <%= form_with model:@genre,url:admin_genre_path do |f| %>
        <%= f.text_field :name %>
        <%= f.submit '変更を保存',class:"btn btn-success" %>
        <% end %>
      </div>
  </div>


</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="ml-5 mb-3 font-weight-bold bg-light">ジャンル一覧・追加</div>
  </div>

  <div class="row mb-3">
    <label class="col-sm-2 font-weight-bold">ジャンル名</label>
      <div class="col-sm-10">
        <%= form_with model:@genre,url:admin_genres_path do |f| %>
        <%= f.text_field :name %>
        <%= f.submit '新規登録',class:"btn btn-success" %>
        <% end %>
      </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-7">
      <table class="table">
        <thead class="table-active">
          <th>ジャンル</th>
          <th></th>
        </thead>
        <tbody>
         <% @genres.each do |genre| %>
          <tr>
            <td>
              <%= genre.name %>
            </td>
           <td>
             <%= link_to "編集する",edit_admin_genre_path(genre.id) %>
           </td>
          </tr>
         <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="ml-5 mb-3 font-weight-bold bg-light">商品新規登録</div>
  </div>
  <div class="d-flex align-items-center justify-content-center">
    <%= form_with model:@item,url:admin_item_path do |f| %>
    <div class="row mb-3">
        <label class="col-sm-4">商品画像</label>
        <div class="col-sm-8">
          <%= f.file_field :image,accept:"image/*" %>
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-sm-4">商品名</label>
        <div class="col-sm-8">
          <%= f.text_field :name %>
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-sm-4">商品説明</label>
        <div class="col-sm-8">
          <%= f.text_area :introduction %>
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-sm-4">ジャンル</label>
        <div class="col-sm-8">
          <%= f.collection_select(:genre_id,@genres,:id,:name) %>
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-sm-4">税抜価格</label>
        <div class="col-sm-8">
          <%= f.number_field :price %>円
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-sm-4">販売ステータス</label>
        <div class="col-sm-4">
          <%= f.radio_button :is_active, :true %><%= "販売中" %>
        </div>
        <div class="col-sm-4">
          <%= f.radio_button :is_active, :false %><%= "販売停止中" %>
        </div>
    </div>

    <div class="mx-auto my-auto">
        <div class="d-flex align-items-center justify-content-center">
            <%= f.submit '変更を保存',class:"btn btn-success" %>
        </div>
    </div>
    <% end %>
 </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
    <div class="row mb-3">
      <div class="col-sm-3">
        <div class="ml-5 mb-3 font-weight-bold bg-light">商品一覧</div>
      </div>
      <div class="col-sm-2 ml-auto">
        <%= link_to "＋" ,new_admin_item_path,class:"btn btn-ligth rounded-circle shadow-sm mb-3 bg-body" %>
      </div>
    </div>
    <table class="table">
      <thead class="table-active">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>販売ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
        <tr>
          <td>
            <%= item.id %>
          </td>
          <td>
            <%= link_to admin_item_path(item.id) do %>
             <%= item.name %>
            <% end %>
          </td>
          <td>
            <%= item.price %>
          </td>
          <td>
            <%= item.genre.name %>
          </td>
          <td>
            <% if item.is_active == true %>
             <%= "販売中" %>
            <% else %>
             <%= "販売停止中" %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="ml-5 mb-3 font-weight-bold bg-light">商品新規登録</div>
  </div>
  <div class="d-flex align-items-center justify-content-center">
    <%= form_with model:@item,url:admin_items_path do |f| %>
    <div class="row mb-3">
        <label class="col-sm-4">商品画像</label>
        <div class="col-sm-8">
          <%= f.file_field :image,accept:"image/*" %>
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-sm-4">商品名</label>
        <div class="col-sm-8">
          <%= f.text_field :name %>
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-sm-4">商品説明</label>
        <div class="col-sm-8">
          <%= f.text_area :introduction %>
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-sm-4">ジャンル</label>
        <div class="col-sm-8">
          <%= f.collection_select(:genre_id,@genres,:id,:name) %>
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-sm-4">税抜価格</label>
        <div class="col-sm-8">
          <%= f.number_field :price %>円
        </div>
    </div>
    <div class="row mb-3">
        <label class="col-sm-4">販売ステータス</label>
        <div class="col-sm-4">
          <%= f.radio_button :is_active, :true %><%= "販売中" %>
        </div>
        <div class="col-sm-4">
          <%= f.radio_button :is_active, :false %><%= "販売停止中" %>
        </div>
    </div>

    <div class="mx-auto my-auto">
        <div class="d-flex align-items-center justify-content-center">
            <%= f.submit '新規登録',class:"btn btn-success" %>
        </div>
    </div>
    <% end %>
 </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <h4>商品詳細</h4>
  <div class="row mb-3">
    <div class="col-4 ">
      <%= image_tag @item.get_image(200,200) %>
    </div>
    <div class="col-sm-8">
      <div class="row mb-3">
        <label class="col-sm-3">商品名</label>
        <div class="col-sm-5">
          <%= @item.name %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-sm-3">商品説明</label>
        <div class="col-sm-6">
          <%= @item.introduction %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-sm-3">ジャンル</label>
        <div class="col-sm-6">
          <%= @item.genre.name %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-sm-3">税込価格</br>（税抜価格）</label>
        <div class="col-sm-6">
          <%= @item.add_tax_price.to_s(:delimited) %><%= "（" %><%= @item.price.to_s(:delimited) %><%= "）円" %>
        </div>
      </div>
      <div class="row mb-3">
        <label class="col-sm-3">販売ステータス</label>
        <div class="col-sm-6">
          <% if @item.is_active == true %>
           <%= "販売中" %>
          <% else %>
           <%= "販売停止中" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="mx-auto my-auto">
    <div class="d-flex align-items-center justify-content-center">
      <%= link_to "編集する",edit_admin_item_path(@item.id),class:"btn btn-success" %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="ml-5 mb-3 font-weight-bold bg-light">注文履歴詳細</div>
  </div>

  <div class="row mb-3">
    <label class="col-sm-2 font-weight-bold">購入者</label>
    <div class="col-sm-10">
      <%= link_to admin_customer_path(@order.customer.id) do %>
      <%= @order.name %>
      <% end %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-2 font-weight-bold">注文日</label>
    <div class="col-sm-10">
      <%= @order.created_at.strftime('%Y/%m/%d') %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-2 font-weight-bold">お届け先</label>
    <div class="col-sm-10">
      〒<%= @order.postal_code %><%= @order.address %></br>
      <%= @order.name %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-2 font-weight-bold">支払方法</label>
    <div class="col-sm-10">
      <%= @order.payment_method_i18n %>
    </div>
  </div>
  <div class="row mb-3">
    <label class="col-sm-2 font-weight-bold">注文ステータス</label>
    <div class="col-sm-10">
      <%= @order.status_i18n %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-8">
      <table class="table table-sm">
        <thead class="table-active">
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
          <th></th>
        </thead>
        <tbody>
         <% @order.order_details.each do |order_detail| %>
          <tr>
            <td class="">
              <%= order_detail.item.name %>
            </td>
           <td class=""><%= order_detail.item.add_tax_price.to_s(:dalimited) %></td>
           <td class="">
             <%= order_detail.amount %>
           </td>
           <td class="">
             <%= order_detail.sub_total.to_s(:dalimited) %>
           </td>
           <td>

           </td>
           <td>
             <%= link_to "更新",admin_path,class:"btn btn-success btn-sm" %>
           </td>
          </tr>
         <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-sm-4 mb-0">
      <div class="row mb-">
        <label class="col-sm-4 font-weight-bold">商品合計</label>
        <div class="col-sm-3">
          <%= (@order.total_payment - @order.shopping_cost).to_s(:delimited) %>円
        </div>
      </div>
      <div class="row mb-2">
        <label class="col-sm-4 font-weight-bold">送料</label>
        <div class="col-sm-3">
          <%= @order.shopping_cost %>円
        </div>
      </div>
      <div class="row mb-2">
        <label class="col-sm-4 font-weight-bold">請求額合計</label>
        <div class="col-sm-3">
          <%= @order.total_payment.to_s(:delimited) %>円
        </div>
      </div>
    </div>
  </div>

</div>