config/routes.rb
Rails.application.routes.draw do

  get '/customers/my_page' => 'public/customers#show'
  get '/customers/information/edit' => 'public/customers#edit'
  patch '/customers/information' => 'public/customers#update'
  get '/customers/unsubscribe' => 'public/customers#unsubscribe'
  patch '/customers/withdraw' => 'public/customers#withdraw'

  get '/orders/complete' => 'public/orders#complete'

  scope module: :public do
    resources:cart_items,only:[:index,:update,:destroy,:create] do
      collection do
        delete "destroy_all"
      end
    end
    resources:addresses,only:[:index,:edit,:create,:update,:destroy]
    resources:items,only:[:index,:show]
    resources:orders,only:[:new,:index,:show,:create]
  end

  post '/orders/comfirm' => 'public/orders#comfirm'
  get '/orders/comfirm' => 'public/orders#comfirm'


    root 'public/homes#top'
    get "/about" => "public/homes#about",as:"about"

    get "/admin" => "admin/homes#top"



  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }

  devise_for :customers,skip:[:passwords],controllers:{
    registrations:"public/registrations",
    sessions:"public/sessions"
  }

  namespace :admin do
    resources:orders,only:[:show,:update]
    resources:genres,only:[:create,:index,:edit,:update]
    resources:items,only:[:index,:new,:create,:show,:edit,:update,:destroy]
    resources:customers,only:[:index,:show,:edit,:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates:postal_code,presence:true
  validates:address,presence:true
  validates:name,presence:true

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  has_one_attached:image
  
  

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  has_one_attached:image
  belongs_to :customer
  belongs_to :item
  
  def sub_total
    item.add_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses,dependent: :destroy
  has_many :cart_items,dependent: :destroy
  has_many :orders,dependent: :destroy

  validates:last_name,presence:true
  validates:first_name,presence:true
  validates:last_name_kana,presence:true
  validates:first_name_kana,presence:true
  validates:postal_code,presence:true
  validates:address,presence:true
  validates:telephone_number,presence:true


def active_for_authentication?
  super && (is_deleted == false)
end

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates:name,presence:true

  has_many :items,dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached:image
  belongs_to :genre
  has_many :cart_items,dependent: :destroy
  has_many :order_details,dependent: :destroy


  validates:name,presence:true
  validates:introduction,presence:true
  validates:price,presence:true
  validates:is_active, inclusion: [true, false]

  def add_tax_price
    (self.price * 1.10).round
  end

  def get_image(width,height)
    unless image.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
    end
     image.variant(resize_to_limit:[width,height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details,dependent: :destroy
  belongs_to :customer

  validates:postal_code,presence:true
  validates:address,presence:true
  validates:name,presence:true

  enum payment_method:{credit_card:0,transfer:1}
  enum status:{deposit_wait:0,deposit:1,making:2,shipping_preparation:3,shipping:4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  validates:price,presence:true
  validates:amount,presence:true

  enum maiking_status:{impossible:0,waiting:1,maiking:2,complete:3}

  def sub_total
    item.add_tax_price * amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page]).order('created_at DESC')

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])

  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end
  
  def destroy
    @item = Item.find(params[:id])
    redirect_to admin_items_path
    @item.destroy
  end

  private
  def item_params
    params.require(:item).permit(:genre_id,:name,:introduction,:price,:is_active,:image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?



  def after_sign_in_path_for(resource)
    "/"
  end

  def after_sign_out_path_for(resource)
    "/"
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <div class="m-2 p-2 vh-100">
    <header class="border border-dark mx-2 my-0">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand py-2 px-5 border border-dark" href="/">
            <span>LOGO</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expand="false" aria-label="Toggle navigation">
            <sppan class="navbar-toggler-icon"></sppan>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
                <li class="nav-item">
                  <%= link_to "マイページ", customers_my_page_path,class:'nav-link text-dark border rounded m-1' %>
                </li>
                <li class="nav-item">
                  <%= link_to "商品一覧", items_path,class:'nav-link text-dark border rounded m-1' %>
                </li>
                <li class="nav-item">
                  <%= link_to "カート", cart_items_path,class:'nav-link text-dark border rounded m-1' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete,class:'nav-link text-dark border rounded m-1' %>
                </li>
              <% else %>
                <% if admin_signed_in? %>
                  <li class="nav-item">
                    <%= link_to "商品一覧",admin_items_path,class:'nav-link text-dark border rounded m-1' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "会員一覧", admin_customers_path,class:'nav-link text-dark border rounded m-1' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "注文履歴一覧", "/admin",class:'nav-link text-dark border rounded m-1' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ジャンル一覧", admin_genres_path,class:'nav-link text-dark border rounded m-1' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class:'nav-link text-dark border rounded m-1' %>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to "About", about_path,class:'nav-link text-dark border rounded m-1' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "商品一覧", items_path,class:'nav-link text-dark border rounded m-1' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "新規登録", new_customer_registration_path,class:'nav-link text-dark border rounded m-1' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログイン", new_customer_session_path,class:'nav-link text-dark border rounded m-1' %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto border border-top-0 border-dark mx-2 p-4 h-75">
      <%= yield %>
    </main>
    <footer class="border border-top-0 border-dark mx-2 p-3 ">
      </br></br>
    </footer>
    </div>
  </body>
</html>